-- #656 B10: 낙상 판정 입력 근거와 결과(LLD-0051 4절).
CREATE TABLE decision_record (
    decision_record_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    decision_id VARCHAR(40) NOT NULL,
    member_id BIGINT NOT NULL,
    run_id VARCHAR(64) NULL,
    stream_ids_used TEXT NOT NULL,
    decision_at_ms BIGINT NOT NULL,
    decision_output VARCHAR(32) NOT NULL,
    decider_id VARCHAR(64) NOT NULL,
    decider_version VARCHAR(64) NOT NULL,
    input_cutoff_ms BIGINT NOT NULL,
    feature_support_end_ms BIGINT NOT NULL,
    model_available_at_server_max_ms BIGINT NOT NULL,
    window_start_ms BIGINT NOT NULL,
    window_end_ms BIGINT NOT NULL,
    alert_id VARCHAR(40) NULL,
    alert_at_ms BIGINT NULL,
    severity VARCHAR(20) NULL,
    trigger_path VARCHAR(40) NULL,
    alert_delivered BOOLEAN NOT NULL,
    trigger_batch_id VARCHAR(26) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT uk_decision_record_decision_id UNIQUE (decision_id),
    INDEX idx_decision_record_run_time (run_id, decision_at_ms),
    INDEX idx_decision_record_member_time (member_id, decision_at_ms),
    INDEX idx_decision_record_trigger_batch (trigger_batch_id)
);
