package com.widyu.admin;

public enum AdminAction {
    ADMIN_LOGIN,
    MEMBER_STATUS_CHANGE,
    FCM_TEST_SEND,
    COLLECTION_RUN_OPEN,
    COLLECTION_RUN_CLOSE,
    STUDY_PARTICIPATION_REGISTER,
    // 값이 운영 DB에 남아 있으므로 이름을 바꾸지 않는다. 보관 계획 수정에 그대로 쓴다.
    STUDY_PARTICIPATION_PERIOD_CHANGE,
    STUDY_PARTICIPATION_WITHDRAW,
    STUDY_PARTICIPATION_DELETION_PROCESSED,
}
