package com.widyu.admin;

public enum AdminAction {
    ADMIN_LOGIN,
    MEMBER_STATUS_CHANGE,
    FCM_TEST_SEND,
    COLLECTION_RUN_OPEN,
    COLLECTION_RUN_CLOSE,
    STUDY_PARTICIPATION_PERIOD_CHANGE,
}
