package com.widyu.fcm.application;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class NotificationSettingMigrationTest {

    @Test
    @DisplayName("기존 설정을 접으면 다섯 항목이 모두 꺼진 회원만 일반 알림을 끈다")
    void 기존_설정을_접으면_모든_일반_항목이_꺼진_회원만_일반_알림을_끈다() throws Exception {
        // given
        Path script = Path.of("scripts/mysql/migrate_notification_setting_group.sql");
        if (!Files.exists(script)) {
            script = Path.of("../../scripts/mysql/migrate_notification_setting_group.sql");
        }
        String content = Files.readString(script);
        String dml = content.substring(content.indexOf("-- H2-DML-BEGIN"), content.indexOf("-- H2-DML-END"));
        dml = dml.replaceAll("(?m)^--.*$", "");
        try (Connection connection = DriverManager.getConnection("jdbc:h2:mem:setting_migration;MODE=MySQL;DB_CLOSE_DELAY=-1");
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE member_notification_setting (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL, category VARCHAR(32) NOT NULL, enabled TINYINT NOT NULL, UNIQUE(member_id, category))");
            statement.execute("INSERT INTO member_notification_setting (member_id, category, enabled) VALUES "
                    + "(1, 'ALBUM', 0), "
                    + "(1, 'MEDICINE_SCHEDULE', 0), (1, 'SAFE_ZONE', 0), "
                    + "(2, 'ALBUM', 0), (2, 'TARGET', 0), (2, 'HEALTH_SCHEDULE', 0), "
                    + "(2, 'WALK', 0), (2, 'ETC', 0), "
                    + "(3, 'ALBUM', 0), (3, 'TARGET', 0), (3, 'HEALTH_SCHEDULE', 0), "
                    + "(3, 'WALK', 0), (3, 'ETC', 1)");

            // when
            for (String command : dml.split(";")) {
                if (command.trim().equalsIgnoreCase("START TRANSACTION")) {
                    continue;
                }
                if (!command.isBlank()) {
                    statement.execute(command.trim());
                }
            }

            // then
            try (ResultSet rows = statement.executeQuery("SELECT member_id, category, enabled FROM member_notification_setting ORDER BY member_id, category")) {
                assertThat(rows.next()).isTrue();
                assertThat(rows.getLong("member_id")).isEqualTo(1L);
                assertThat(rows.getString("category")).isEqualTo("MEDICATION_CHECK");
                assertThat(rows.getInt("enabled")).isZero();
                assertThat(rows.next()).isTrue();
                assertThat(rows.getLong("member_id")).isEqualTo(2L);
                assertThat(rows.getString("category")).isEqualTo("GENERAL");
                assertThat(rows.getInt("enabled")).isZero();
                assertThat(rows.next()).isFalse();
            }
        }
    }
}
