spring:
  application:
    name: WIDYU-backend
  profiles:
    group:
      local: "local, datasource, fcm, pay, s3"
      dev: "dev, datasource, fcm, pay, s3"
      test: "test, fcm, pay, s3"
      pilot: "pilot, datasource, fcm, pay, s3"

    include:
      - security
      - coolsms
      - redis
      - imp
      - oauth
      - video
      - pay
      - medicine
      - actuator
      - ai
      - juso

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

swagger:
  version: ${SWAGGER_VERSION:0.0.1}
  url: ${SWAGGER_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    urls-primary-name: 전체 API

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level traceId=%X{traceId:-none} [%thread] %logger{36} - %msg%n"
