spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
