apiVersion: 1

contactPoints:
  - orgId: 1
    name: widyu-development-discord
    receivers:
      - uid: widyu-development-discord
        type: discord
        settings:
          url: $DISCORD_WEBHOOK_URL
          title: "{{ .CommonLabels.alertname }}"
          message: "{{ .CommonAnnotations.summary }}\ntraceId: {{ .CommonAnnotations.trace_id }}\n{{ .CommonAnnotations.grafana_url }}"
